### ISSUE TITLE
CartKit Status

### ISSUE THREAD

**Issue by heyallan** [dsply/Cartkit#1]
Few questions here:
- What's the current status of cartkit? any roadmap?
- Can you add the status to the top of the README.md file?
- How likely you are to discuss new features? (here's where the roadmap comes in handy).

**Comment by heyallan** [comment]
BTW Awesome plugin :+1:

**Comment by shash7** [comment]
Same here, looks really promising.

**Comment by starckio** [comment]
I have work yet.
Let me informed you soon.
Promised!
